"""add webviz field

Revision ID: 0a162d39fac1
Revises: e1d46906479e
Create Date: 2023-07-19 16:06:42.890591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a162d39fac1'
down_revision = 'e1d46906479e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webviz', sa.String(length=200), nullable=True, comment='webviz'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webviz_path', sa.Text(), nullable=False, comment='webviz的存放路径'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('webviz_path')

    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.drop_column('webviz')

    # ### end Alembic commands ###
