"""add model path field of project

Revision ID: 30fbfd191508
Revises: 9b72a746b0ee
Create Date: 2023-05-10 17:04:37.072693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30fbfd191508'
down_revision = '9b72a746b0ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lidar_path', sa.Text(), nullable=False, comment='激光模型的存放路径'))
        batch_op.add_column(sa.Column('camera_path', sa.Text(), nullable=False, comment='视觉模型的存放路径'))
        batch_op.add_column(sa.Column('map_path', sa.Text(), nullable=False, comment='地图数据的存放路径'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=mysql.VARCHAR(length=100),
               comment='验证登录有效性',
               existing_comment='验证登录有效性的token',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=mysql.VARCHAR(length=100),
               comment='验证登录有效性的token',
               existing_comment='验证登录有效性',
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('map_path')
        batch_op.drop_column('camera_path')
        batch_op.drop_column('lidar_path')

    # ### end Alembic commands ###
