"""add sdc_path field on Project table

Revision ID: 4423271af327
Revises: de2b0b76aba9
Create Date: 2023-06-07 10:27:19.902901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4423271af327'
down_revision = 'de2b0b76aba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sdc', sa.String(length=200), nullable=True, comment='SDC数据'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sdc_path', sa.Text(), nullable=True, comment='SDC的存放路径'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('sdc_path')

    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.drop_column('sdc')

    # ### end Alembic commands ###
