"""add personal jenkins job

Revision ID: 4ca7533dcaf8
Revises: c28418cffef1
Create Date: 2023-05-15 10:01:23.992425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca7533dcaf8'
down_revision = 'c28418cffef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_name_p', sa.Text(), nullable=False, comment='jenkins构建个人任务的名称'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('job_name_p')

    # ### end Alembic commands ###
