"""modify field attribute of lidar/camera/map

Revision ID: 535fd4c638d5
Revises: c4dff3aeaedb
Create Date: 2023-05-25 13:41:23.051447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '535fd4c638d5'
down_revision = 'c4dff3aeaedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.alter_column('lidar',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='激光模型')
        batch_op.alter_column('camera',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='视觉模型')
        batch_op.alter_column('map',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='地图数据')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.alter_column('map',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='地图数据')
        batch_op.alter_column('camera',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='视觉模型')
        batch_op.alter_column('lidar',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='激光模型')

    # ### end Alembic commands ###
