"""add plan_map field

Revision ID: 996582550e8a
Revises: 515b60690654
Create Date: 2023-06-16 16:40:51.129086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996582550e8a'
down_revision = '515b60690654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_map', sa.String(length=200), nullable=True, comment='规划地图数据'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_map_path', sa.Text(), nullable=False, comment='规划地图数据的存放路径'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('plan_map_path')

    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.drop_column('plan_map')

    # ### end Alembic commands ###
