"""add lidar/camera/map field of app_process

Revision ID: c28418cffef1
Revises: 30fbfd191508
Create Date: 2023-05-11 10:25:01.025429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c28418cffef1'
down_revision = '30fbfd191508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_process', schema=None) as batch_op:
        batch_op.alter_column('job_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_comment='jenkins构建任务的名称',
               existing_nullable=False)

    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lidar', sa.String(length=100), nullable=False, comment='激光模型'))
        batch_op.add_column(sa.Column('camera', sa.String(length=100), nullable=False, comment='视觉模型'))
        batch_op.add_column(sa.Column('map', sa.String(length=100), nullable=False, comment='地图数据'))
        batch_op.alter_column('job_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_comment='jenkins构建任务的名称',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.alter_column('job_name',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_comment='jenkins构建任务的名称',
               existing_nullable=False)
        batch_op.drop_column('map')
        batch_op.drop_column('camera')
        batch_op.drop_column('lidar')

    with op.batch_alter_table('api_process', schema=None) as batch_op:
        batch_op.alter_column('job_name',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_comment='jenkins构建任务的名称',
               existing_nullable=False)

    # ### end Alembic commands ###
