"""modify artifacts_url field type

Revision ID: c4dff3aeaedb
Revises: 4ca7533dcaf8
Create Date: 2023-05-24 17:01:18.803526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4dff3aeaedb'
down_revision = '4ca7533dcaf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_process', schema=None) as batch_op:
        batch_op.alter_column('jenkins_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_comment='jenkins构建的url',
               existing_nullable=True)
        batch_op.alter_column('artifacts_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_comment='artifactory的url',
               existing_nullable=True)
        batch_op.alter_column('confluence_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_comment='confluence的url',
               existing_nullable=True)

    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.alter_column('jenkins_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_comment='jenkins构建的url',
               existing_nullable=True)
        batch_op.alter_column('artifacts_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_comment='artifactory的url',
               existing_nullable=True)
        batch_op.alter_column('confluence_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_comment='confluence的url',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.alter_column('confluence_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_comment='confluence的url',
               existing_nullable=True)
        batch_op.alter_column('artifacts_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_comment='artifactory的url',
               existing_nullable=True)
        batch_op.alter_column('jenkins_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_comment='jenkins构建的url',
               existing_nullable=True)

    with op.batch_alter_table('api_process', schema=None) as batch_op:
        batch_op.alter_column('confluence_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_comment='confluence的url',
               existing_nullable=True)
        batch_op.alter_column('artifacts_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_comment='artifactory的url',
               existing_nullable=True)
        batch_op.alter_column('jenkins_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_comment='jenkins构建的url',
               existing_nullable=True)

    # ### end Alembic commands ###
