"""add auto_test

Revision ID: d19f4f66203f
Revises: 4423271af327
Create Date: 2023-06-07 16:32:51.429599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19f4f66203f'
down_revision = '4423271af327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_test', sa.Integer(), nullable=True, comment='是否自动化测试'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_name_test', sa.Text(), nullable=False, comment='jenkins构建测试任务的名称'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('job_name_test')

    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.drop_column('auto_test')

    # ### end Alembic commands ###
