"""add driver_path field

Revision ID: de2b0b76aba9
Revises: 535fd4c638d5
Create Date: 2023-06-01 10:27:56.498537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de2b0b76aba9'
down_revision = '535fd4c638d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_process', schema=None) as batch_op:
        batch_op.alter_column('job_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='jenkins构建任务的名称',
               existing_nullable=False)
        batch_op.alter_column('desc',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='描述',
               existing_nullable=True)

    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver', sa.String(length=200), nullable=True, comment='驱动数据'))
        batch_op.alter_column('api_version',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_comment='接口版本号',
               existing_nullable=True)
        batch_op.alter_column('lidar',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='激光模型',
               existing_nullable=True)
        batch_op.alter_column('camera',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='视觉模型',
               existing_nullable=True)
        batch_op.alter_column('map',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='地图数据',
               existing_nullable=True)
        batch_op.alter_column('job_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='jenkins构建任务的名称',
               existing_nullable=False)
        batch_op.alter_column('desc',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='描述',
               existing_nullable=True)

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.alter_column('git',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_comment='git',
               existing_nullable=False)
        batch_op.alter_column('desc',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='描述',
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_path', sa.Text(), nullable=True, comment='驱动的存放路径'))
        batch_op.alter_column('desc',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='描述',
               existing_nullable=True)

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='描述',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_comment='描述',
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_comment='描述',
               existing_nullable=True)
        batch_op.drop_column('driver_path')

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_comment='描述',
               existing_nullable=True)
        batch_op.alter_column('git',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_comment='git',
               existing_nullable=False)

    with op.batch_alter_table('app_process', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_comment='描述',
               existing_nullable=True)
        batch_op.alter_column('job_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_comment='jenkins构建任务的名称',
               existing_nullable=False)
        batch_op.alter_column('map',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_comment='地图数据',
               existing_nullable=True)
        batch_op.alter_column('camera',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_comment='视觉模型',
               existing_nullable=True)
        batch_op.alter_column('lidar',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_comment='激光模型',
               existing_nullable=True)
        batch_op.alter_column('api_version',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_comment='接口版本号',
               existing_nullable=True)
        batch_op.drop_column('driver')

    with op.batch_alter_table('api_process', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_comment='描述',
               existing_nullable=True)
        batch_op.alter_column('job_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_comment='jenkins构建任务的名称',
               existing_nullable=False)

    # ### end Alembic commands ###
